volumes:
  excalistore: 

services:
  excalidraw-client:
    container_name: excalidraw
    image: excalidraw/excalidraw:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HOSTNAME=${HOSTNAME}
    restart: always
    ports:
      - 443:443
      - 3000:3000
      - 3002:3002

  excalidraw-room:
    container_name: excaliroom
    image: excalidraw/excalidraw-room:latest
    restart: always
    environment:
      PORT: 3002
      HOSTNAME: ${HOSTNAME}

  excalidraw-storage:
    container_name: excalistore
    image: excalistore:latest
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    environment:
      HOSTNAME: "${HOSTNAME}"
    volumes:
      - excalistore:/opt/node/data
