volumes:
  excalistore: 

services:
  excalidraw-client:
    container_name: excalidraw
    image: excalidraw:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      VITE_APP_BACKEND_V2_GET_URL: http://${HOSTNAME}:3000/api/v2/
      VITE_APP_BACKEND_V2_POST_URL: http://${HOSTNAME}:3000/api/v2/post/
      VITE_APP_WS_SERVER_URL: http://${HOSTNAME}:3002

    ports:
      - 80:80

  excalidraw-room:
    container_name: excaliroom
    image: excalidraw/excalidraw-room:latest
    restart: always
    environment:
      PORT: 3002

  excalidraw-storage:
    container_name: excalistore
    image: excalistore:latest
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    environment:
      HOSTNAME: "${HOSTNAME}"
    volumes:
      - excalistore:/opt/node/data
    ports:
      - 3000:3000
    